#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.

# Install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAproxy to use round-robin algorithm
sudo sed -i 's/.*balance.*/balance roundrobin/' /etc/haproxy/haproxy.cfg

# Configure HAproxy to forward traffic to web-01 and web-02
sudo sed -i '/^backend web-servers$/a\    server web-01 100.25.182.144:80 check\n    server web-02 52.87.18.57:80 check' /etc/haproxy/haproxy.cfg

# Configure HAproxy to be managed via init script
sudo sed -i 's/ENABLED=.*/ENABLED=1/' /etc/default/haproxy

# Restart HAproxy service
sudo service haproxy restart
